18-rails-review/football_manager/config/routes.rb
Rails.application.routes.draw do

  resources :players, :teams, :managers, :fans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

18-rails-review/football_manager/app/models/fan.rb
class Fan < ApplicationRecord
  has_many :fan_teams
  has_many :teams, through: :fan_teams
end

18-rails-review/football_manager/app/models/fan_team.rb
class FanTeam < ApplicationRecord
  belongs_to :fan
  belongs_to :team
end

18-rails-review/football_manager/app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :team
end

18-rails-review/football_manager/app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

18-rails-review/football_manager/app/models/team.rb
class Team < ApplicationRecord
  has_many :players
  has_one :manager
  has_many :fan_teams
  has_many :fans, through: :fan_teams
end

18-rails-review/football_manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

18-rails-review/football_manager/app/controllers/fans_controller.rb
class FansController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

18-rails-review/football_manager/app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

18-rails-review/football_manager/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show

  end

  def new
    @player = Player.new
    @teams  = Team.all
  end

  def create
    @player = Player.create(player_params)
    redirect_to @player
  end

  def edit
    @teams = Team.all
  end

  def update
    @player.update(player_params)
    redirect_to @player
  end

  def destroy
    @player.destroy
    redirect_to players_path
  end


  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :position, :number, :team_id)
  end

end

18-rails-review/football_manager/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

18-rails-review/football_manager/app/helpers/fans_helper.rb
module FansHelper
end

18-rails-review/football_manager/app/helpers/managers_helper.rb
module ManagersHelper
end

18-rails-review/football_manager/app/helpers/player_helper.rb
module PlayerHelper
end

18-rails-review/football_manager/app/helpers/teams_helper.rb
module TeamsHelper
end

18-rails-review/football_manager/app/views/fans/edit.html.erb
<h1>Fans#edit</h1>
<p>Find me in app/views/fans/edit.html.erb</p>

18-rails-review/football_manager/app/views/fans/index.html.erb
<h1>Fans#index</h1>
<p>Find me in app/views/fans/index.html.erb</p>

18-rails-review/football_manager/app/views/fans/new.html.erb
<h1>Fans#new</h1>
<p>Find me in app/views/fans/new.html.erb</p>

18-rails-review/football_manager/app/views/fans/show.html.erb
<h1>Fans#show</h1>
<p>Find me in app/views/fans/show.html.erb</p>

18-rails-review/football_manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

18-rails-review/football_manager/app/views/managers/edit.html.erb
<h1>Managers#edit</h1>
<p>Find me in app/views/managers/edit.html.erb</p>

18-rails-review/football_manager/app/views/managers/index.html.erb
<h1>Managers#index</h1>
<p>Find me in app/views/managers/index.html.erb</p>

18-rails-review/football_manager/app/views/managers/new.html.erb
<h1>Managers#new</h1>
<p>Find me in app/views/managers/new.html.erb</p>

18-rails-review/football_manager/app/views/managers/show.html.erb
<h1>Managers#show</h1>
<p>Find me in app/views/managers/show.html.erb</p>

18-rails-review/football_manager/app/views/players/_form.html.erb
<%= form_for @player do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :position %>
<%= f.text_field :position %>

<%= f.label :number %>
<%= f.text_field :number %>

<%= f.label :team %>
<%= f.collection_select :team_id, @teams, :id, :name %>

<%= f.submit %>
<% end %>

18-rails-review/football_manager/app/views/players/edit.html.erb
<h1>Edit Player - <%= @player.name %></h1>

<%= render 'form' %>

<%= link_to "Go Back", players_path %>

<%= form_for @player, method: :delete do |f|%>
<%= f.submit "Delete" %>
<% end %>

<%= link_to "Delete Player", player_path(@player), method: :delete %>

<%= form_tag("/players/#{@player.id}", method: :delete) %>
<%= submit_tag("delete") %>

18-rails-review/football_manager/app/views/players/index.html.erb
<h1>All Players</h1>

<ul>
<% @players.each do |player| %>
  <li><%= link_to player.name, player_path(player) %></li>
<% end %>
</ul>

<%= link_to "Create Player", new_player_path %>

18-rails-review/football_manager/app/views/players/new.html.erb
<h1>Create New Player</h1>

<%= render 'form' %>

18-rails-review/football_manager/app/views/players/show.html.erb
<h1>Player - <%= @player.name %></h1>
<h1>Position - <%= @player.position %></h1>
<h1>Number - <%= @player.number %></h1>
<h1>Team - <%= @player.team.name %></h1>


<%= link_to "Back to Index", players_path %>
<%= link_to "Edit Player", edit_player_path(@player) %>