19-rails_auth/docoffice/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :doctors

  # user management
  get "/signup", to: 'users#new', as: 'signup'
  post "/signup", to: 'users#create'
  get "/users/:id", to: 'users#show', as: 'user'

  # sessions management
  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy', as: 'logout'
end

19-rails_auth/docoffice/app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :office
  has_many :visits
  has_many :patients, through: :visits

  validates :name, uniqueness: true, presence: true, length: { minimum: 2 }
  validates :specialty, presence: true, length: { minimum: 2 }
end

19-rails_auth/docoffice/app/models/office.rb
class Office < ApplicationRecord
  has_many :doctors
end

19-rails_auth/docoffice/app/models/patient.rb
class Patient < ApplicationRecord
  has_many :visits
  has_many :doctors, through: :visits
end

19-rails_auth/docoffice/app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
  has_secure_password
end

19-rails_auth/docoffice/app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

19-rails_auth/docoffice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    else
      User.new
    end
  end

  def logged_in?
    !!current_user.id
  end

  def authorized?
    if !logged_in?
      flash[:authorized] = "You are not logged in"
      redirect_to login_path and return
    end
  end

  def authorized_for(user_id)
    if current_user.admin == true
      true
    elsif current_user.id != user_id.to_i
      flash[:authorized] = "You cannot view a page that does not belong to you"
      redirect_to doctors_path
    end
  end
end

19-rails_auth/docoffice/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :find_doctor, only: [:show, :edit, :update, :destroy]
  def index
    @doctors = Doctor.all
  end

  def show
    byebug
  end

  def new
    @doctor = Doctor.new
    @offices = Office.all
    @patients = Patient.all
  end

  def create
    @doctor = Doctor.create(doctor_params)
    if @doctor.valid?
      redirect_to doctor_path(@doctor)
    else
      flash[:errors] = @doctor.errors.full_messages
      redirect_to new_doctor_path
    end
  end

  def edit
    @offices = Office.all
    @patients = Patient.all
  end

  def update
    @doctor.update(doctor_params)
    if @doctor.valid?
      redirect_to @doctor
    else
      flash[:errors] = @doctor.errors.full_messages
      redirect_to edit_doctor_path(@doctor)
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private

  def find_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :specialty, {patient_ids: []}, :office_id)
  end
end

19-rails_auth/docoffice/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to doctors_path
    else
      flash[:errors] = ["Invalid username or password"]
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

19-rails_auth/docoffice/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    authorized_for(params[:id])
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to doctors_path
    else
      redirect_to new_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

19-rails_auth/docoffice/app/views/doctors/_form.html.erb
<%= form_for @doctor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :specialty %>
  <%= f.text_field :specialty %>

  <%
    # c_s takes 5 arguments, but 1 here is implicit cause we're in a form_for
    # the implicit argument is the model that you create the c_s for.
    # please ignore it! for all intents and purposes here, we don't care now
    # 1 property of the target model that you want to set (doctor.office_id)
    # 2 collection of stuff you want to choose from! (comes from the controller)
    # 3 property that you want to use as a value for no.1 (doctor.office_id = office.id)
    # 4 whatcha wanna show on the page (office.name)
  %>
  <br>
  <%= f.collection_select(:office_id, @offices, :id, :name) %>

  <br>
  <%= f.collection_check_boxes(:patient_ids, @patients, :id, :name) %>
  <br>
  <%= f.submit %>
<% end %>

19-rails_auth/docoffice/app/views/doctors/edit.html.erb
<h1> Edit a doctor </h1>

<%= link_to 'cancel', doctors_path %>

<%= render "form" %>

<%= form_tag("/doctors/#{@doctor.id}", method: "delete") do %>
  <%= submit_tag("delete") %>
<% end %>

19-rails_auth/docoffice/app/views/doctors/index.html.erb
<h1> All doctors</h1>

<%= link_to 'create a new doctor', new_doctor_path %>

<ul>
  <% @doctors.each do |doc| %>
    <li>
      <%= link_to doc.name, doc %>
    </li>
  <% end %>
</ul>

19-rails_auth/docoffice/app/views/doctors/new.html.erb
<h1> Create a new doctor </h1>

<%= link_to 'cancel', doctors_path %>

<%= render "form" %>

19-rails_auth/docoffice/app/views/doctors/show.html.erb
<h1>This is <%= @doctor.name %>'s page</h1>
<p>They work as a <%= @doctor.specialty %></p>
<p>And their office is in <%= @doctor.office.name %></p>

<% if @doctor.patients.length > 0 %>
  <p>This doctor is treating following patients:</p>
  <ul>
    <% @doctor.patients.each do |p| %>
      <li>
        <%= p.name %>
      </li>
    <% end %>
  </ul>
<% end %>



<%= link_to 'edit me', edit_doctor_path %>
<%= link_to 'go back', doctors_path %>

19-rails_auth/docoffice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docoffice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |e|  %>
          <li style="color: red;"><%= e %></li>
        <% end %>
      </ul>
    <% end %>

    <div>
     <% if logged_in? %>
       <p> You are logged in as <%= link_to current_user.username, current_user %> </p>
       <p> <%= link_to "Log out", logout_path, method: "post" %> </p>

       <% if current_user.admin == true %>
         <p> You are an admin </p>
       <% else %>
         <p> You are a user </p>
       <% end %>

     <% else %>
       <p> You are not logged in. </p>
       <p> <%= link_to "Log in?", login_path %> </p>
       <p> or </p>
       <p> <%= link_to "Sign up?", signup_path %> </p>
     <% end %>
   </div>

   <% if flash[:authorized] %>
     <p> <%= flash[:authorized] %> </p>
   <% end %>

    <%= yield %>
  </body>
</html>

19-rails_auth/docoffice/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user, :url => "/signup" do |f| %>
  <%= f.label :username  %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit %>
<% end %>

19-rails_auth/docoffice/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= link_to 'go back', '/doctors' %>